language: r
sudo: true
dist: xenial
latex: false
pandoc: false
warnings_are_errors: false
cache:
  packages: true
  directories:
  - "/tmp/texlive"
  - "$HOME/.TinyTeX"
  - "$HOME/.texlive"
install: echo "Nothing occurs at installation, only script"
script:
  - mkdir _build
  - Rscript install_texlive.R
  - Rscript -e 'tinytex::pdflatex("cv/Deependra_CV.tex", bib_engine = "biber", engine_args
  = "--no-shell-escape", pdf_file = "_build/Deependra_CV.pdf")'
  - Rscript -e 'tinytex::pdflatex("cv/Deependra_CV_simple.tex", bib_engine = "biber", 
  engine_args = "--no-shell-escape", pdf_file = "_build/Deependra_CV_simple.pdf")'
branches:
  - master
  - "/v\\d+\\.\\d+[a-z]/"
before_deploy:
  - git config --local user.name "DeependraD"
  - git config --local user.email "dean.ionized@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: MIsrRs/aXgKCJJ2ptb9B5eB+XvwRaGjpI9BxVjOA0jQTJVVIS0FEVHPDLsrhHeie0pY4lnUDqqu30F0fHkh15NVDP/gOMPDHED6N2fTLinWfF2eko2QfDsmWZZJkRD2ZrQZZhRCEoiLZVDHDm7vYQ5YlxskM/lUdvrhc38ELDwaSy1rutrw47Yz6IkHAigSaRlZFuSsSmaz4LBmi8N7E826lLBBTe48MIVpDd1j3cBy8vXsHZy53SpP1Rtv4cH8ZFuGsgiJ3faxZ6RvrsnqIBBHQ/wUgKMBCMv6F0pGZCvMDvFzJYHGG7GTx5Y3X4e7DAtWGJZJt4UyH7od/geEiNiPojie2LYPOCInVsesDkcCpSo/7YOgSZz6/qrUnDqb0XaQw8PB7BuJI4hgMy4hmW6igVRcmfenrpCPp/u1crDl5Pbx8Ol6f2obVVHayeVI+3sNIjiOY7SUzZe5rbjCothk5sfsjGiuG3+DG/vBIHBp0oIBlLFuPgPPLFjdAOjG03SUtlPW9CaRiVkhLzgThzs7Zy2z8bRIu+WslG8+MgOmQP9x/xjcTjqYmn9MqJBzk/h4jFMxSE92L933mNEeSUFhEJPW5QzyfyDgChtrKpzXFuVfIdlfDgPqovNRKwaGXCie+Dxfu3gmuxRG4OBYCSRSmSm5BVCMtNBdP4CTo+Zg=
  file: 
    - _build/Deependra_CV.pdf
    - _build/Deependra_CV_simple.pdf
  on:
    repo: DeependraD/tex-for-beauty
    tags: true
  skip_cleanup: 'true'
