language: r
sudo: true
dist: xenial
latex: false
pandoc: false
warnings_are_errors: false
cache:
        packages: true
        directories:
                - /tmp/texlive
                - $HOME/.TinyTeX
                - $HOME/.texlive
install: echo "Nothing occurs at installation, only script"
script:
        - mkdir _build
        - Rscript install_texlive.R
        - Rscript -e 'tinytex::pdflatex("cv/Deependra_CV.tex", bib_engine = "biber", engine_args = "--no-shell-escape")'
        - Rscript -e 'tinytex::pdflatex("cv/Deependra_CV_simple.tex", bib_engine = "biber", engine_args = "--no-shell-escape")'
branches:
          - master
before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "DeependraD"
      - git config --local user.email "dean.ionized@gmail.com"
      - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
      - git tag $TRAVIS_TAG
deploy:
        provider: releases
        overwrite: true        
        skip_cleanup: true 
        github_token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
        api_key:
              secure: <generated by `travis setup releases>
        local_dir: _build/
        file: 
                - Deependra_CV.pdf
                - Deependra_CV_simple.pdf
        on:
                rep: DeependraD/tex-for-beauty
                tags: true
