\documentclass[20pt]{beamer}
\usepackage[size=a0, orientation=portrait, scale=1.4]{beamerposter} % scale multiplies the font size of document class i.e. 20 x 1.4 = 28
\usepackage{graphicx}
\graphicspath{{images/}}

\setbeamercolor{background canvas}{bg=green!75}
\setbeamercolor{colorheadlinemine}{fg=white, bg=red}
\setbeamertemplate{headline}{%
\begin{beamercolorbox}[wd=\paperwidth]{colorheadlinemine}

\begin{columns}

  \begin{column}{0.15\linewidth}
    \includegraphics[width=0.85\linewidth]{afu-logo}
  \end{column}

  \begin{column}{0.85\linewidth}
  \centering\bfseries
  {\fontsize{80}{96}\selectfont Post anthesis leaf health as potential determinant of yield in early evaluation trial of wheat genotypes} \\[6mm]
  {\fontsize{60}{72}\selectfont Deependra Dhakal} \\[6mm]
  {\fontsize{48}{60}\selectfont Department of Plant Breeding, Agriculture and Forestry University} \\
  {\fontsize{36}{42}\selectfont Bharatpur, Chitwan} \\
  {\fontsize{36}{42}\selectfont Email: \url{ddhakal.rookie@gmail.com}}
  \end{column}

\end{columns}
\end{beamercolorbox}

\color{red}\rule{\paperwidth}{20pt}
}
\setbeamercolor{colorfootlinemine}{fg=white, bg=red!20}
\setbeamertemplate{footline}{
\begin{beamercolorbox}[wd=\paperwidth]{colorfootlinemine}
  {\small For highlights of my work: \url{ddhakal.rookie@gmail.com}}
\end{beamercolorbox}
}

\begin{document}
\SweaveOpts{concordance=TRUE}
\begin{frame}[t]

\begin{columns}[t]

%==============================col-1==================
\begin{column}{0.32\linewidth}

\begin{block}{Introduction}


\end{block}


\begin{block}{Introduction}

\end{block}


\end{column}
%==============================col-2==================
\begin{column}{0.32\linewidth}

\begin{block}{Introduction}

\end{block}

\begin{block}{Introduction}

\end{block}


\end{column}
%==============================col-3==================
\begin{column}{0.32\linewidth}

\begin{block}{Introduction}

\end{block}

\begin{block}{Introduction}

\end{block}

\begin{block}{Introduction}

\end{block}

\begin{block}{Introduction}

\end{block}


\end{column}
\end{columns}







\end{frame}
\end{document}
